select * from customer limit 10;


-- Q1. What is the total revenue generated by male vs. female customers?
select gender,sum(purchase_amount) as total_revenue
from customer
group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer)
order by purchase_amount desc;


-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(cast(review_rating as decimal(10,2))),2) as rating
from customer
group by item_purchased
order by rating desc
limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type,round(avg(purchase_amount),2) as purchase_amount
from customer
where shipping_type IN ('Express', 'Standard')
group by shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status, 
	count(subscription_status) as subscription_count,
	round(avg(purchase_amount),2) as avg_purchase_amount,
	sum(purchase_amount) as total_revenue
from customer
group by subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased, round(100*sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as discount_apply
from customer
group by item_purchased
order by discount_apply desc
limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as (
select customer_id,previous_purchases,
case
	when previous_purchases = 1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal' end as customer_segment
from customer
)
select customer_segment,count(*) as "Number of customer"
from customer_type
group by customer_segment;

-- Q8. What are the top 3 most purchased products within each category?
with item_count as(
select category,item_purchased,count(customer_id) as total_orders,
row_number() over(partition by category  order by count(customer_id) desc) as item_rank
from customer
group by category,item_purchased
)
select item_rank,category,item_purchased,total_orders
from item_count
where item_rank <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
 select subscription_status,count(customer_id) as total_customer
 from customer
 where previous_purchases > 5
 group by subscription_status;

-- Q10. What is the revenue contribution of each age group?
select age_group,sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;

--Q11 Show all customers who purchased items in the Winter season.
select count(customer_id) as Total_customer_in_winter
from customer
where season = 'Winter';

--Q12 Find the average age of customers.
select round(avg(age),2) as "Average age(years)"
from customer;

--Q13 Retrieve customers from a specific location (e.g., "New York").
select customer_id
from customer
where location = 'New York';

--Q14 Calculate the total revenue generated from each product category.
select category,sum(purchase_amount) as revenue
from customer
group by category
order by revenue desc;

--Q15 List all customers who gave a review rating above 4.
select customer_id,review_rating
from customer
where review_rating >4;

--Q16 Find the percentage of purchases where shipping type = “Express”.
select round(100*sum(case when shipping_type = 'Express' then 1 else 0 end)::numeric/count(*)::numeric,2) 
	as "Express Shipping Usage in %"
from customer;